version: '3.7'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile

    image: fencilux/ecommerce
    ports:
      - 3000:3000
    # command: ["yarn", "fencilux"]
    command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USERNAME: admin
      DB_PASSWORD: secret
      COOKIE_SECRET: secret
      DB: postgres

  postgres:
    image: postgres:12.3
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c pg_stat_statements.max=100000 -c max_connections=200
  pgadmin:
    image: dpage/pgadmin4:4.18
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.dev
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    links:
      - "postgres:pgsql-server"
volumes:
  postgres_data:
    driver: local

  pgadmin_data:
    driver: local
